steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/wdc-roster-backend:latest'
      - '-f'
      - 'dockerfile'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/wdc-roster-backend:latest'
timeout: 600s
